### ISSUE TITLE
overload error

### ISSUE THREAD

**Issue by zhengzhuoxun** [vortexntnu/stim300#6] opened 2021-05-18 22:03 UTC
Hi! Thank you very much for your code, it helps me a lot. 
However I have met the error: "Stim 300 IMU overload."

I have read the datasheet of the sensor, it said "If time between triggers is longer than 8ms, an overload may occur..." But I have checked that the sample frequence is 125hz. I have even tried to configurate the frequence to 250hz by the stim's software in windows, but it still doesn't work. I have also checked that the default configuration in code is same with the actual configuration, which is also setted up using the software in windows...

And the sensor works well in windows with the software.

Do you have any idea how to solve this problem?

Thank you very much!

**Comment by AndreasVaage** [comment] 2021-05-26 13:21
Hi, it’s been a while since I have worked with the IMU, but I will try to help you out. First of I can’t remember running in to this before and don’t know if this error have been properly tested so there is a chance there is just a bug in the driver. 

What the driver does is that just accumulate all the status bytes from the different sensors on the IMU into one and then check that status byte with respect to the table in section 6.4 in the datashet.

Assuming the driver is working as intended this means the IMU set the overflow bit in the status byte for one of the sensors.

The sentence from the datasheet you refer to is regarding the external triggering option, meaning an input pulse signal from the computer tells the IMU exactly when to perform measurements. So if the triggering is to sparse, accumulated gyro measurements within the IMU will overflow. I assume you are not operating in external triggering mode and instead just configure the imu to sample at 125 hz or 250 hz. Then that should not be a problem.

However I believe the overflow error can also be caused in normal operation (I.e not in external triggering mode), as I think it is raised whenever the accelerometer sensors measure above 10% of their specified range. I.e if you have a 5g version and shake the IMU really hard so it measures a acceleration of 5.5g I believe this will cause this error.

If this error occurs in every measurement even when the IMU is standing still, you could try to use minicom or some other serial monitor to do a single shot measurement like in Figure 10-20: “Example of response from a (SINGLE-SHOT MEASUREMENT) command with error flagging” from the datasheet. To see if the error is there as well.

**Comment by zhengzhuoxun** [comment] 2021-06-09 08:30
Hi, thank you very much for your reply, it helps me a lot.

At first I thought it was something wrong in the driver, where I didn't configure correctly, that caused this problem. After reading your reply, I checked the Manufacturer supplied software in windows again, and have found out that the OVERLOAD problem also happens, which I didn't realize before. 

After that I have been communicating with the support from the manufacture and found out that this is a hardware issue, I plan to return this unit back for further troubleshooting.

Thank you very much again for your help!

**Comment by AndreasVaage** [comment] 2021-06-09 08:45
Hi, thank you for the update. Glad I could be of some help and hope the IMU will be fixed. I'll close this issue.

**Closed as completed by AndreasVaage** 2021-06-09 08:45 UTC
